# Pegar directamente con Ctrl+V sin necesidad de Shift
map ctrl+v paste_from_clipboard

# Clic derecho estilo Windows:
# Si hay texto seleccionado: lo copia al portapapeles y deselecciona.
# Si no hay texto seleccionado: pega el portapapeles.
mouse_map right press ungrabbed kitten mouse_action.py
mouse_map shift+right press ungrabbed,grabbed kitten mouse_action.py

# Transparencia (0.70 igual que Alacritty)
background_opacity 0.70
dynamic_background_opacity yes

# Tamaño inicial de ventana (no maximizada, dimensiones estilo Alacritty)
remember_window_size no
initial_window_width 100c
initial_window_height 30c
